### ISSUE TITLE
tag links don't work ... many are empty when you click on them

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/addons.silverstripe.org#135]
![image](https://cloud.githubusercontent.com/assets/167154/19658144/59ba27e6-9a83-11e6-9270-503795e0e0f3.png)

![image](https://cloud.githubusercontent.com/assets/167154/19658154/612ca6c0-9a83-11e6-96e5-8f4e829a014e.png)

**Comment by rrymrrsn** [comment]
Yes I have found this to be a problem too. Would be good to get it fixed as I find it quite difficult to find add-ons that do exactly what I need as it is.

**Comment by robbieaverill** [comment]
Ok I've done a quick investigation, here's a little more context:

* The `tag` key references in `AddonsController::Addons` has changed to `tags`. Switching this re-enables simple* tag filtering
* \*: Tags with dashes in them are [analysed by ElasticSearch](https://stackoverflow.com/questions/11566838/elastic-search-hyphen-issue-with-term-filter) and handled as two separate terms. You can see by the fact that `ecommerce` returns results, but `e-commerce` doesn't, since no addons are tagged with "e" and "commerce". Also searching for `silverstripe-[anything]` will return all addons, since "silverstripe" is a tag that all addons have

We probably need to ensure that addon names and tags (at least) are not analysed when creating our field mappings. It also may end up being easier to do as the linked Stackoverflow answer above suggests and switch to using text queries, but that might also involve more rewriting throughout the codebase.

Re-labelling as higher impact since this essentially is breaking a large part of expected search functionality.

**Comment by dhensby** [comment]
is this fixed now?

**Comment by robbieaverill** [comment]
Yeah, but it hasn't been deployed yet. The initial problem in that no tags work in search is fixed with #163, but it's still difficult to perform multi word searches, or searches with dashes in them (ElasticSearch query modifier) will still not work. Can close this issue for now.
