### ISSUE TITLE
Search sometimes gives wrong Results

### ISSUE THREAD

**Issue by AngryPHPNerd** [silverstripe/addons.silverstripe.org#84]
Somtimes the search gives wrong results.

For example if I search for the subsite module:
![search_issue](https://cloud.githubusercontent.com/assets/905241/4733227/df33859e-59c5-11e4-9ac6-e961f2d66ee9.png)

I think it is an issue with the IDs in the search index, because if I wait some minutes the result is correct:
![subsites-2](https://cloud.githubusercontent.com/assets/905241/4733297/9e35e978-59c6-11e4-8401-810c4acbda64.png)

**Comment by Martimiz** [comment]
+1 for that.

Again others are mentioning the same issue, and I feel it may be somewhat undermining the addons section as an important part of promoting SilverStripe to the world? 

http://www.silverstripe.org/community/forums/all-other-modules/show/97192

I'd really like to help, but on this particular module I just wouldn't know where to start :(

**Comment by anselmdk** [comment]
Just tried to search for my calendar module like this: http://addons.silverstripe.org/add-ons?search=calendar&type=&sort=newest, and no calendar-related modules appeared...

So yes, I'm also experiencing it.

**Comment by anselmdk** [comment]
To my opinion the search is completely broken. I think this should be a high priority, as it makes it almost impossible to use the site for finding modules.

**Comment by Martimiz** [comment]
At this point, for me at least, google is the only way :(

Martine

**Comment by camfindlay** [comment]
Hey guys, yip I agree. I have that at the very top of my backlog to see if we can get some devs in-house working on this.

**Comment by micmania1** [comment]
There was a few issues here.

*New Modules Not Showing Up*
This was caused by composer not being able to parse a version constraint. It was throwing an exception when trying to validate '^3.1.0' which is valid in new versions of composer, but an old version of composer was packaged with the addons site. This has been updated.

*Irrelevant Search Results*
Because of the validation issues, tasks were unable to complete. This meant there was issues updating and re-indexing. It looks like the elastic search index was not matching up with the new or partly updated addons. This is resolved for now, however I suspect there may be an issue with when the addons are re-indexed compared to when the addons are updated. (ie. The addons are being updated but not immediately re-indexed). I want to monitor this and if it proves to be an issue I can work towards a fix.

If anybody spots any of the issues above, please let me know in this ticket.

**Comment by anselmdk** [comment]
I'm afraid the search still doesn't work. I just tried to search for "calendar", and the result (http://addons.silverstripe.org/add-ons?search=calendar) showed a lot of unrelated posts, but not my calendar (which explicitly has "calendar" as a keyword: https://github.com/titledk/silverstripe-calendar/blob/1.0/composer.json)

![screenshot 2015-01-28 08 33 15](https://cloud.githubusercontent.com/assets/1316533/5933963/726841ca-a6c8-11e4-82ea-52c6af8b44da.png)

**Comment by micmania1** [comment]
I've just re-indexed then searched again and its showing relevant results. I'm pretty sure I've figured out what the issue is so i'll get more time on it and implement a proper fix.

**Comment by wilr** [comment]
It also gives you far too many results. Indexing requires some level of finesse, blurry keywords or something similar. Example: 

If I search for 'sitetree hide page' to find a module to hide pages from the site tree I would expect to see modules with those keywords.

URL: http://addons.silverstripe.org/add-ons?search=sitetree+hide+page&type=&sort=

Expected near the top: 
https://github.com/micmania1/silverstripe-lumberjack
https://github.com/micschk/silverstripe-excludechildren

But instead get display logic and userforms, perhaps need user defined keywords for modules?

**Comment by camfindlay** [comment]
Hey all, can you try the search today. I have searched for 'calendar' (as @anselmdk did) this morning and have got good results and 2 pages (rather than 25 that @wilr reports). Hopefully that means that @micmania1 has managed to get this fixed.

![add ons silverstripe add ons](https://cloud.githubusercontent.com/assets/367847/5993597/f0288944-aaba-11e4-9ad2-abfae8bd1779.png)

**Comment by Martimiz** [comment]
Unfortunately his still doesn't look quite right :(

![image](https://cloud.githubusercontent.com/assets/614243/5993636/8b83a07c-aa57-11e4-9896-04432971c9e5.jpg)

**Comment by Martimiz** [comment]
Unfortunately stis still doesn't look quite right :(
![image](https://cloud.githubusercontent.com/assets/614243/5993690/0764cb8e-aa59-11e4-9b08-9a968c410b77.jpg)

**Comment by camfindlay** [comment]
I think @micmania1 still has to look at changing the timing of the indexing and building modules from packagist. Are you still actively working on this @micmania1 ?

**Comment by micmania1** [comment]
Running a local test as I type this :)

**Comment by micmania1** [comment]
I've deployed some fixes to live and it should now all be working.

The main reason it didn't work was because there's a test site on the same server which was using the same elastic search index. I've made a change to ensure its always different.

There was also various other fixes along the way including a few bugs which prevented the addons site from updating properly.

If you spot anything else related to this just respond here.

**Comment by camfindlay** [comment]
This seems to be fixed now :)

**Comment by camfindlay** [comment]
Although I have just searched again and got some strange results... http://addons.silverstripe.org/add-ons?search=blog&type=&sort=

@micmania1 any ideas?

![screen shot 2015-02-04 at 6 27 34 pm](https://cloud.githubusercontent.com/assets/367847/6035606/95a7f53a-ac9b-11e4-9c24-667852d27626.png)

**Comment by micmania1** [comment]
This is fixed again.

I changed the ss environment file to make the staging site 'test' so that I could use it to distinguish between environments. The server was recently restarted which runs puppet scripts and overwrote the changes I made.

I've now made the changes to puppet which will stop this happening in the future.

**Comment by camfindlay** [comment]
awesome thanks.
